version: '3.8'
services:
  db:
    image: postgres:15
    container_name: starcash_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: starcash_admin
      POSTGRES_PASSWORD: starcash_secure_password
      POSTGRES_DB: starcash_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: